/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type VoteValue = "down" | "up";

export interface MediaAttachments {
  display_order: number;
  filename: string;
  id: Generated<string>;
  mime_type: string;
  post_id: string;
  uri: string;
}

export interface Posts {
  content: string;
  created_at: Generated<Timestamp>;
  creator_display_name: string;
  creator_id: string;
  creator_username: string;
  deleted_at: Timestamp | null;
  downvotes: Generated<number>;
  id: Generated<string>;
  score: Generated<number>;
  title: string;
  updated_at: Generated<Timestamp>;
  upvotes: Generated<number>;
}

export interface PostVotes {
  created_at: Generated<Timestamp>;
  post_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  value: VoteValue;
}

export interface RefreshTokens {
  expires_at: Timestamp;
  token: Generated<string>;
  user_id: string;
}

export interface Users {
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  email_verification_expires_at: Timestamp | null;
  email_verification_token_hash: string | null;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  password_hash: string;
  username: string;
}

export interface DB {
  media_attachments: MediaAttachments;
  post_votes: PostVotes;
  posts: Posts;
  refresh_tokens: RefreshTokens;
  users: Users;
}
